<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="USPL-310" failures="1" tests="5" name="Personal Loan" time="0.081" errors="0" timestamp="2025-04-16T18:10:21 IST">
  <testcase classname="basics.Day2" name="ploan" time="0.006"/>
  <testcase classname="basics.Day1" name="demo" time="0.02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at basics.Day1.demo(Day1.java:14)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase classname="basics.Day4" name="loginAPIHomeLoan" time="0.002"/>
  <testcase classname="basics.Day4" name="mobileLoginHomeLoan" time="0.002"/>
  <testcase classname="basics.Day4" name="webLoginHomeLoan" time="0.001"/>
  <testcase classname="basics.Day1" name="secondTest" time="0.0">
    <ignored/>
  </testcase> <!-- secondTest -->
</testsuite> <!-- Personal Loan -->
